### ISSUE TITLE
Is it work on Hololens?

### ISSUE THREAD

**Issue by Xyy1209** [Firifire/OpenCvHololens#2]

**Comment by picolino0** [comment]
Yes. I asked the same thing more or less in #1. I managed to get it to work and I posted a build, since none are provided.

**Comment by Xyy1209** [comment]
Thanks very much for your reply! I download your project serving by the link. However, when i build the 'test scene ' in the project  ,there is some problem .

Plugin 'OpenCvSharp.dll' is used from several locations:
 Assets/Plugins/UWP/OpenCvSharp.dll would be copied to <PluginPath>/OpenCvSharp.dll
 Assets/Plugins/Standalone/OpenCvSharp.dll would be copied to <PluginPath>/OpenCvSharp.dll
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

I guess it is that the 'opencvsharp.dll' existing in both 'standalone' file and 'UWP' file caused the problem.
Maybe i should change the 'platform' in the inspector of the  two 'opencvsharp.dll' ? I am not sure.Would you please give me some help?  Thanks!!

**Comment by picolino0** [comment]
That's probably right yes.
The DLLs in the UWP folder are x86 (because you have to compile UWP projects for the HoloLens as x86). They should be set to x86 as well then. In the UWP tab you shouldn't have to change anything.
The other DLLs are x86_64. I disabled UWP support for them as you can't compile x86_64 for HoloLens anyway.

I thought those settings would carry over in a unitypackage (meta files and all that), but apparently it didn't. Hopefully this will help you a little bit.
